### ISSUE TITLE
Cannot install story-branch on Windows

### ISSUE THREAD

**Issue by Grepsy** [story-branch/story_branch#72] opened 2019-06-14 10:18 UTC
I'm trying to install this on Windows with a fresh Ruby installation (especially installed to use this) but installation fails with the following error:

```
>gem install story_branch
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing story_branch:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/levenshtein-ffi-1.1.0/ext/levenshtein
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20190614-20824-mavm9z.rb extconf.rb
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/levenshtein-ffi-1.1.0/ext/levenshtein
make "DESTDIR=" clean

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/levenshtein-ffi-1.1.0/ext/levenshtein
make "DESTDIR="
generating levenshtein-x64-mingw32.def
compiling levenshtein.c
linking shared-object levenshtein.so
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export Init_levenshtein: symbol not defined
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:259: levenshtein.so] Error 1

make failed, exit code 2
```

I've tried searching for the error but can't find any useful information. Any pointers to what I might do to get this working?

In the README of levenshtein I read:

> This function can be used as a drop-in replacement for
Text::Levenshtein.levenshtein, which is pure Ruby and rather slow. That's it!

Not sure how important the perf. is in the program, but it might be possible to use the pure Ruby impl. if it doesn't matter so it's not dependent on the native lib?

**Comment by rpbaltazar** [comment] 2019-06-17 15:03
I have not tried it in windows as i don't have a running machine. Let me boot a windows VM and see what i find. Might be the case that levenshtein is causing the problems.

I'll also test with the drop in replacement. The performance shouldn't be seriously affected because this is only used to check wether you already have a similar branch.

**Comment by rpbaltazar** [comment] 2019-06-20 07:14
Just a quick heads up, I've finally had time to setup a windows VM and try it myself. 
I do get the same error, which is good because it means I can reproduce it and try to fix it.

looking at the levenshtein gem we are using, [there is an open issue](https://github.com/dbalatero/levenshtein-ffi/issues/8) for windows installation which the owner as not replied in a very long time, so I assume it won't be fixed. 

I'll proceed with testing with other gem and see if it does not cause issues on story branch

**Comment by Grepsy** [comment] 2019-06-20 07:32
Thank you for looking into this; really appreciate it!

**Closed** 2019-06-20 07:54 UTC

**Comment by rpbaltazar** [comment] 2019-06-20 07:58
I just published the new version 0.5.2 which i've tested in my windows vm and it is possible to install it and use it. Give it a try and let me know if you run into any other issues.

**Comment by Grepsy** [comment] 2019-06-20 10:51
Worked like a charm! Thanks!

**Comment by rpbaltazar** [comment] 2019-06-21 02:44
Great news. Enjoy and give me any feedback you might have.
